version: "3.7"
services:
  db:
    image: mongo
    container_name: simple-mongo-db
    env_file:
      - .env
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017-27019:27017-27019"
    networks:
      - default
